#!/bin/zsh
set -euo pipefail

repo_dir="${0:A:h:h}"
vault_dir="${OBSIDIAN_VAULT:-$HOME/Documents/CCNA}"
sync_branch="agent/obsidian-sync"

cd "$repo_dir"

if [[ "$(git branch --show-current)" != "$sync_branch" ]]; then
  print -u2 "Refusing to run outside $sync_branch"
  exit 2
fi

if [[ -n "$(git status --porcelain)" ]]; then
  print -u2 "Refusing to run with uncommitted repository changes"
  exit 2
fi

if ! gh auth status >/dev/null 2>&1; then
  print -u2 "GitHub authentication is unavailable. Run: gh auth refresh -h github.com"
  exit 2
fi

git fetch origin main
if git merge-base --is-ancestor HEAD origin/main; then
  git merge --ff-only origin/main
fi

/usr/bin/python3 automation/sync_obsidian.py --vault "$vault_dir" --repo "$repo_dir"

git add -A -- README.md ACTIVITY.md notes progress .obsidian-sync-manifest.json
if ! git diff --cached --quiet; then
  git commit -m "Sync Obsidian learning activity $(date +%F)"
else
  print "No new publishable Obsidian changes found."
fi

git push -u origin "$sync_branch"

if ! gh pr list --repo Burperryberry/ccna-learning-portfolio --head "$sync_branch" --state open --json number --jq 'length > 0' | grep -q '^true$'; then
  body_file="$(mktemp -t ccna-obsidian-sync-pr)"
  trap 'rm -f "$body_file"' EXIT
  printf '%s\n' \
    '## What changed' \
    '' \
    '- Synced publishable CCNA notes from the Obsidian vault.' \
    '- Refreshed GitHub-friendly Anki and Packet Tracer progress pages.' \
    '- Updated the README current topic and recent activity links.' \
    '' \
    '## Safety' \
    '' \
    '- Excludes Obsidian internals, trash, tracker state, and Packet Tracer binaries.' \
    '- Honors `publish: false` in note frontmatter.' \
    '- Stops before committing when a high-confidence secret pattern is detected.' \
    '' \
    '## Validation' \
    '' \
    '- Generated by `automation/sync_obsidian.py`.' > "$body_file"
  gh pr create \
    --repo Burperryberry/ccna-learning-portfolio \
    --base main \
    --head "$sync_branch" \
    --draft \
    --title "Sync CCNA Obsidian learning activity" \
    --body-file "$body_file"
fi
