#!/bin/zsh
set -euo pipefail

repo_dir="${0:A:h:h}"
sync_branch="agent/anki-sync"
collection="${ANKI_COLLECTION:-$HOME/Library/Application Support/Anki2/User 1/collection.anki2}"
lock_dir="${TMPDIR:-/tmp}/com.burperryberry.ccna-anki-sync.lock"

if ! mkdir "$lock_dir" 2>/dev/null; then
  print "Anki sync is already running."
  exit 0
fi
trap 'rmdir "$lock_dir" 2>/dev/null || true' EXIT

cd "$repo_dir"

if [[ "$(git branch --show-current)" != "$sync_branch" ]]; then
  print -u2 "Refusing to run outside $sync_branch"
  exit 2
fi

if [[ -n "$(git status --porcelain)" ]]; then
  print -u2 "Refusing to run with uncommitted repository changes"
  exit 2
fi

if ! gh auth status -h github.com >/dev/null 2>&1; then
  print -u2 "GitHub authentication is unavailable. Run: gh auth refresh -h github.com"
  exit 2
fi

git fetch origin main
if git merge-base --is-ancestor HEAD origin/main; then
  git merge --ff-only origin/main
elif ! git merge-base --is-ancestor origin/main HEAD; then
  print -u2 "The automation branch diverged from origin/main; manual reconciliation is required."
  exit 2
fi

/usr/bin/python3 automation/export_anki_progress.py \
  --collection "$collection" \
  --repo "$repo_dir"

git add -- progress/anki.md "flashcard-progress/Anki Progress Dashboard.md"
if ! git diff --cached --quiet; then
  git commit -m "Sync Anki progress $(date +%F)"
else
  print "No new Anki progress changes found."
fi

git push -u origin "$sync_branch"

if ! git diff --quiet origin/main...HEAD; then
  has_open_pr="$(gh pr list \
    --repo Burperryberry/ccna-learning-portfolio \
    --head "$sync_branch" \
    --state open \
    --json number \
    --jq 'length > 0')"
  if [[ "$has_open_pr" != "true" ]]; then
    body_file="$(mktemp -t ccna-anki-sync-pr)"
    trap 'rm -f "$body_file"; rmdir "$lock_dir" 2>/dev/null || true' EXIT
    printf '%s\n' \
      '## What changed' \
      '' \
      '- Refreshed the public CCNA Anki progress dashboards.' \
      '- Added aggregate workload, review activity, streak, and weak-topic metrics.' \
      '' \
      '## Privacy' \
      '' \
      '- Does not publish card questions, answers, note fields, or raw review history.' \
      '- Reads a temporary snapshot and never modifies the live Anki collection.' \
      '' \
      '## Automation' \
      '' \
      '- Generated by the local nightly Anki sync at 8:00 PM.' > "$body_file"
    gh pr create \
      --repo Burperryberry/ccna-learning-portfolio \
      --base main \
      --head "$sync_branch" \
      --draft \
      --title "Sync Anki learning progress" \
      --body-file "$body_file"
  fi
fi
